package Kamarad;


/**
* Kamarad/_KamaradProviderImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Kamarad.idl
* 11 March 2014 16:39:53 o'clock GMT
*/

public abstract class _KamaradProviderImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements Kamarad.KamaradProvider, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _KamaradProviderImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("register", new java.lang.Integer (0));
    _methods.put ("getDetails", new java.lang.Integer (1));
    _methods.put ("topupAccount", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //Register
       case 0:  // Kamarad/KamaradProvider/register
       {
         Kamarad.KamaradAccountDetails accountDetails = Kamarad.KamaradAccountDetailsHelper.read (in);
         org.omg.CORBA.AnyHolder uniqueId = new org.omg.CORBA.AnyHolder ();
         this.register (accountDetails, uniqueId);
         out = $rh.createReply();
         out.write_any (uniqueId.value);
         break;
       }


  //Return balance - retrieve the entire record
       case 1:  // Kamarad/KamaradProvider/getDetails
       {
         int uniqueId = in.read_long ();
         Kamarad.KamaradAccountDetailsHolder accountDetails = new Kamarad.KamaradAccountDetailsHolder ();
         this.getDetails (uniqueId, accountDetails);
         out = $rh.createReply();
         Kamarad.KamaradAccountDetailsHelper.write (out, accountDetails.value);
         break;
       }


  //Topup
       case 2:  // Kamarad/KamaradProvider/topupAccount
       {
         int uniqueId = in.read_long ();
         double amount = in.read_double ();
         this.topupAccount (uniqueId, amount);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Kamarad/KamaradProvider:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _KamaradProviderImplBase
