package Kamarad;


/**
* Kamarad/KamaradProvider_Tie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Kamarad.idl
* 11 March 2014 17:41:53 o'clock GMT
*/

public class KamaradProvider_Tie extends _KamaradProviderImplBase
{

  // Constructors
  public KamaradProvider_Tie ()
  {
  }

  public KamaradProvider_Tie (Kamarad.KamaradProviderOperations impl)
  {
    super ();
    _impl = impl;
  }


  //Register
  public void register (Kamarad.KamaradAccountDetails accountDetails, org.omg.CORBA.AnyHolder uniqueId)
  {
    _impl.register(accountDetails, uniqueId);
  } // register


  //Return balance - retrieve the entire record
  public void getDetails (int uniqueId, Kamarad.KamaradAccountDetailsHolder accountDetails)
  {
    _impl.getDetails(uniqueId, accountDetails);
  } // getDetails


  //Topup
  public void topupAccount (int uniqueId, double amount)
  {
    _impl.topupAccount(uniqueId, amount);
  } // topupAccount

  private Kamarad.KamaradProviderOperations _impl;

} // class KamaradProvider_Tie
