package Kamarad;


/**
* Kamarad/KamaradProviderHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Kamarad.idl
* 11 March 2014 17:41:53 o'clock GMT
*/

abstract public class KamaradProviderHelper
{
  private static String  _id = "IDL:Kamarad/KamaradProvider:1.0";

  public static void insert (org.omg.CORBA.Any a, Kamarad.KamaradProvider that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Kamarad.KamaradProvider extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Kamarad.KamaradProviderHelper.id (), "KamaradProvider");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Kamarad.KamaradProvider read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_KamaradProviderStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Kamarad.KamaradProvider value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Kamarad.KamaradProvider narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Kamarad.KamaradProvider)
      return (Kamarad.KamaradProvider)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Kamarad._KamaradProviderStub stub = new Kamarad._KamaradProviderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Kamarad.KamaradProvider unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Kamarad.KamaradProvider)
      return (Kamarad.KamaradProvider)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Kamarad._KamaradProviderStub stub = new Kamarad._KamaradProviderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
