package Kamarad;


/**
* Kamarad/KamaradProvider.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Kamarad.idl
* 11 March 2014 17:41:53 o'clock GMT
*/

public interface KamaradProvider extends KamaradProviderOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface KamaradProvider
