package Kamarad;


/**
* Kamarad/KamaradProviderOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Kamarad.idl
* 11 March 2014 16:39:53 o'clock GMT
*/

public interface KamaradProviderOperations 
{

  //Register
  void register (Kamarad.KamaradAccountDetails accountDetails, org.omg.CORBA.AnyHolder uniqueId);

  //Return balance - retrieve the entire record
  void getDetails (int uniqueId, Kamarad.KamaradAccountDetailsHolder accountDetails);

  //Topup
  void topupAccount (int uniqueId, double amount);
} // interface KamaradProviderOperations
